### ISSUE TITLE
Calling the Same Method in a for-loop

### ISSUE THREAD

**Issue by Mishost** [VasiPeycheva/Data-Structures-and-Algorithms--2018-2019#2]
In the file DynamicArrayAlgorithms.h on lines 26 and 30 you are calling a method, respectively First.getSize() and Second.getSize(), every time you iterate over the elements of the arrays. This is from the function merge().

Same goes for the next function, includes(). On line 44 you are calling the method Second.getSize() on every iteration of the loop.

The same problem exists on line 67 in the function filter().

All of this can be made faster by creating a new variable which will be assigned with the size you need. This way, you will be calling the method once, instead of numerous times.

**Comment by IvanFilipov** [comment]
Generally you are right, but notice that nowadays the compilers are much smarter than they used to be. Even without specific flags for optimization, the code generated by them won't make a call to _getSize() _ or similar method, a cache value will be used instead, which is almost the same as you suggested.
