### ISSUE TITLE
stoi() instead of atoi(<cast to cstring>)

### ISSUE THREAD

**Issue by IcoBoyanov** [VasiPeycheva/Data-Structures-and-Algorithms--2018-2019#3]
You can use stoi(<string>) to directly cast to int.
In Student.h line : 32 
		data.age = atoi(age.c_str());  --> data.age = stoi(age);

http://www.cplusplus.com/reference/string/stoi/

Also stol (long), stoll(long long)... 

Поздрави,
Ицо

**Comment by VasiPeycheva** [comment]
Thank you for your advice! I will correct it!
