### ISSUE TITLE
SubNodes counting without using a bool variable

### ISSUE THREAD

**Issue by mom4ilakis** [VasiPeycheva/Data-Structures-and-Algorithms--2018-2019#5]
bool insert(node *& root, int data)
{

	if (data == root->data)
		return false;

	if (data < root->data)
	{
		if (!root->left)
		{
			root->left = new node(data);
			root->subNodes++;
			return true;
		}

		if (insert(root->left, data))
		{
			root->subNodes++;
			return true;
		}
	}
	else
	{

		if (!root->right)
		{
			root->right = new node(data);
			root->subNodes++;
			return true;
		}

		if (insert(root->right, data))
		{
			root->subNodes++;
			return true;
		}

	}

	return false;
}

**Comment by VasiPeycheva** [comment]
Thank you for your implementation code for the BST insert function Momchil! 
You have some implementation mistakes(what will happen if root is nullptr?) 
BUT i really appreciate the fact that you spend time for this task. You will get 1 bonus point for your effort!
