### ISSUE TITLE
An Additional if-statement

### ISSUE THREAD

**Issue by Mishost** [VasiPeycheva/Data-Structures-and-Algorithms--2018-2019#6]
On the following line of code: https://github.com/VasiPeycheva/Data-Structures-and-Algorithms--2018-2019/blob/65715ec06d11384a2fb153f753202cbd9d6a6f1b/Practice_08--Trees/solutions/task2_solution/task2.cpp#L42

in the function _insert_helper_, the compiler will go over an additional if-statement. 

The problem is that if _element_ is greater than _root->key_, the code in the previous else-if statement will be executed. In other words, we shouldn't make the compiler check if _element_ is smaller than _root->key_.

This can be fixed by turning the if-statement into an else-if statement.

**Comment by VasiPeycheva** [comment]
Thank you very much Mishosh for your remark! The function is now correctly updated.
